# Generated by Django 3.2 on 2021-05-11 04:36

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorlist',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='donorlist',
            name='last_donate_date',
        ),
        migrations.AddField(
            model_name='donorlist',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(blank=True, map_id='map', null=True),
        ),
        migrations.AddField(
            model_name='donorlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='donorlist',
            name='last_donated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorlist',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': (77.21987228649732, 28.630981392199445), 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'}, null=True),
        ),
        migrations.AddField(
            model_name='donorlist',
            name='willing_to_donate_plasma',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donorlist',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donorlist',
            name='cardiac',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True),
        ),
    ]
