# Generated by Django 3.2 on 2021-04-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0002_auto_20191219_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorlist',
            name='willing_to_donate_plasma',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True),
        ),
    ]
