# Generated by Django 3.2 on 2021-05-07 13:56

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0003_donorlist_willing_to_donate_plasma'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorlist',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': (17.031645, 51.106715), 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'}, null=True),
        ),
    ]
