# Generated by Django 3.2 on 2021-05-07 13:59

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0004_donorlist_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorlist',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(blank=True, map_id='map', null=True),
        ),
        migrations.AddField(
            model_name='donorlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
