# Generated by Django 3.2 on 2021-05-10 08:18

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0006_remove_donorlist_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorlist',
            name='last_donate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorlist',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': (77.21987228649732, 28.630981392199445), 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'}, null=True),
        ),
    ]
