# Generated by Django 3.2 on 2021-05-07 14:59

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0006_remove_donorlist_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorlist',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': (28.7041, 77.1025), 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'}, null=True),
        ),
    ]
