# Generated by Django 3.2 on 2021-05-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0007_auto_20210510_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorlist',
            name='last_donate_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
