# Generated by Django 3.2 on 2021-04-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0002_auto_20191219_0103'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=10)),
                ('units', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreg.donorlist')),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.requestedrecord')),
            ],
        ),
    ]
