# Generated by Django 3.2 on 2021-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210508_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedrecord',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
