# Generated by Django 3.2 on 2021-05-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_requestedrecord_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedrecord',
            name='emergency',
            field=models.CharField(blank=True, choices=[('urgently_required', 'Urgently Required'), ('pick_a_date', 'Pick a date')], max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='requestedrecord',
            name='required_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
