# Generated by Django 3.2 on 2021-05-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20210511_1342'),
        ('search', '0006_auto_20210511_1743'),
    ]

    operations = [
    ]
